// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBdFvSq6LZ8mM-zLsPULNCJUsEMFun9Jlg',
    appId: '1:252893953804:ios:e614176a3b6200fafe9329',
    messagingSenderId: '252893953804',
    projectId: 'birthday-buddy-b5db0',
    storageBucket: 'birthday-buddy-b5db0.firebasestorage.app',
    iosBundleId: 'com.birthdaybuddy.birthday',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyArjSAyEMl4oVd4L9dnfbK3_mAn7YdPrwA',
    appId: '1:252893953804:android:2303f83386f6b09ffe9329',
    messagingSenderId: '252893953804',
    projectId: 'birthday-buddy-b5db0',
    storageBucket: 'birthday-buddy-b5db0.firebasestorage.app',
  );

}